### ISSUE TITLE
Does not exist in the current contest errors.

### ISSUE THREAD

**Issue by Bannerlordz** [TheC0mpany/GrowtopiaStealer#1]
I really liked to look of your stealer and the features but i had so many errors here is the errors:

`1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Growtopia.cs(20,13,20,21): error CS0103: The name 'Counting' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Discord.cs(21,71,21,76): error CS0103: The name 'Paths' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Discord.cs(26,21,26,29): error CS0103: The name 'Counting' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(26,32,26,41): error CS0117: 'DiscordWebhook' does not contain a definition for 'FakeError'
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(27,48,27,64): error CS0117: 'DiscordWebhook' does not contain a definition for 'FakeErrorMessage'
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(53,13,53,26): error CS0103: The name 'Visual_Studio' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(119,57,119,67): error CS0103: The name 'SystemInfo' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(121,46,121,56): error CS0103: The name 'SystemInfo' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(122,58,122,68): error CS0103: The name 'SystemInfo' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(123,47,123,57): error CS0103: The name 'SystemInfo' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(124,47,124,57): error CS0103: The name 'SystemInfo' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(125,47,125,57): error CS0103: The name 'SystemInfo' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(126,49,126,54): error CS0103: The name 'BSSID' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(135,33,135,41): error CS0103: The name 'Counting' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(136,33,136,41): error CS0103: The name 'Counting' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(137,33,137,41): error CS0103: The name 'Counting' does not exist in the current context
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(158,42,158,51): error CS0117: 'Buffer' does not contain a definition for 'GetBuffer'
1>C:\Users\atlas\Desktop\GrowtopiaStealer-main\GrowtopiaStealer\Program.cs(192,13,192,23): error CS0103: The name 'Screenshot' does not exist in the current`

**Comment by TheC0mpany** [comment]
I now done with V5 i can reuploud all of that stealer one moment

**Comment by TheC0mpany** [comment]
Done try now download source code

**Comment by TheC0mpany** [comment]
Reply to me it work for u?

**Comment by Bannerlordz** [comment]
> Reply to me it work for u?

It builds perfectly without any errors when i try to open it tho it doesnt even give the fake error message or the discord bot.
btw if you have any decoder i hacked a 2magplant account

**Comment by Bannerlordz** [comment]
> Reply to me it work for u?

Okay thank you very much it worked rn but still do you know any decoders by any chance?
cuz they changed the encoding thing the decoders on github doesnt work

**Comment by TheC0mpany** [comment]
You need change false to true: https://github.com/TheC0mpany/GrowtopiaStealer/blob/55183ac201345c5d3a164dc9104fcdbb79d9deb0/GrowtopiaStealer/DiscordWebhook.cs#L16
If you want change message default message: Application failed to start. 0x09000b
You need change it here https://github.com/TheC0mpany/GrowtopiaStealer/blob/55183ac201345c5d3a164dc9104fcdbb79d9deb0/GrowtopiaStealer/DiscordWebhook.cs#L17

**Comment by TheC0mpany** [comment]
> > Reply to me it work for u?
> 
> Okay thank you very much it worked rn but still do you know any decoders by any chance?
> cuz they changed the encoding thing the decoders on github doesnt work

I trying to add to stealer save.dat password decoder
