### ISSUE TITLE
Discord WebHook  Error, Warnings.

### ISSUE THREAD

**Issue by SagexWasTaken** [TheC0mpany/GrowtopiaStealer#7]
Whenever trying to build this app it keeps on not letting me cause an error and possible warnings. - 
![image](https://user-images.githubusercontent.com/65954052/140207950-e3db98e4-c018-4c11-8e34-4663fcdca088.png)

Warnings include same looking stuff about Webhook. Thanks if there's a resolution!

**Comment by TheC0mpany** [comment]
Idk for me all works good.
Maybe u dont have "JNogueira.Discord.Webhook.Client" installed
![image](https://user-images.githubusercontent.com/65458800/140224655-8f846b89-247c-4ec2-9dcf-917fb07b2365.png)
